### ISSUE TITLE
[FEAT] Show Current Grades 

### ISSUE THREAD

**Issue by Varun-Kolanu** [Varun-Kolanu/csoc_flutter#10]
**Describe the solution you'd like**
- Display the subject wise marks and Grade expected by user, and credits
- Display the Expected SPI according to the credits entered in the subject

**Additional context**
UI:

![image](https://github.com/Varun-Kolanu/csoc_flutter/assets/112728411/1c01fa68-0e4f-4b13-898c-41f9609b19da)

**Comment by rashiranjan22** [comment]
@csoc-bot claim
