### ISSUE TITLE
[FEAT] Add / Edit Subject Page

### ISSUE THREAD

**Issue by Varun-Kolanu** [Varun-Kolanu/csoc_flutter#2]
**Is your feature request related to a problem? Please describe.**
The page for creating or editing subjects isn't there yet.

**Describe the solution you'd like**
- User should be able to create Subject in his collection
- User should be able to edit the subject info
- Subject contains Name, Days, Credits
- No need to change the widget AppBar. A new issue is there for it.

Bonus: Add Location of class as current location. If it seems hard, it will be created as a new issue don't worry

**Describe alternatives you've considered**
UI is not fixed. You have liberty to edit the UI

**Additional context**
Rough wireframe of UI:
 
![image](https://github.com/Varun-Kolanu/csoc_flutter/assets/112728411/c8ce8016-3182-41b7-83c5-75260405788d)

Full Figma: https://www.figma.com/design/SSqE8Fn9qAakayjyhZ9gqf/Attendance-Tracker?node-id=0-1&t=Xpgi43pHobRh2dnD-1

**Comment by criticic** [comment]
trying to test something @csoc-bot claim

**Comment by criticic** [comment]
Hmm, did it try to assign itself? (because the term is in its own comment)

**Comment by Varun-Kolanu** [comment]
> Hmm, did it try to assign itself? (because the term is in its own comment)

Yeah I have forgot to not include csoc-bot in assigning. Will change :)

**Comment by criticic** [comment]
is the calendar sort fo feature a priority right now? like i think just the days is not enough, because on each specific day class timing maybe different

**Comment by Varun-Kolanu** [comment]
@criticic Yeah we are reminding user to mark his attendance if today is in the timetable of a subject. Timing doesn't matter actually because user can choose when to remind him to mark. 

If there are two classes in each day, he can add an extra class. 

Yeah this is for attendance feature only. Further issues are being created for different features

**Comment by Varun-Kolanu** [comment]
Hmm nice. We can add that now too if you would like to update the UI according to the needs. Rather than putting days horizontally, we can stack them vertically and timing can be put adjacent to each day. Or else, it can be postponed to later issues

**Comment by Varun-Kolanu** [comment]
@criticic How's the work going on. Any issues?

**Comment by devrungta** [comment]
@criticic I was assigned the issue to add the subjects page and in order to successfully check out it's functioning, I have aldo added the appropriate methods to add the subjects, now if it is possible, please review the pr mentioned above and add the edit subject button as well since I was unable to do so.
Thank you

**Comment by criticic** [comment]
I will send a PR for this by the weekend, was a bit busy and outside.

**Comment by devrungta** [comment]
also can you incorporate the edit subject in the home screen to make sure that when marking attendance also, an api call is made to change the fields in the firebase database.
Thank you
