### ISSUE TITLE
[FEAT] Display the subjects of User

### ISSUE THREAD

**Issue by Varun-Kolanu** [Varun-Kolanu/csoc_flutter#3]
**Is your feature request related to a problem? Please describe.**
No page exists to display user's subjects

**Describe the solution you'd like**
- Display the subjects of user on the screen

**Additional context**
Rough UI (You have liberty to modify):

![image](https://github.com/Varun-Kolanu/csoc_flutter/assets/112728411/8c3b2467-6ab3-41a6-aabb-f1a33a3d9488)

Full figma: https://www.figma.com/design/SSqE8Fn9qAakayjyhZ9gqf/Attendance-Tracker?node-id=0-1&t=Xpgi43pHobRh2dnD-1

**Comment by devrungta** [comment]
@csoc-bot claim
