### ISSUE TITLE
[FEAT] Home Screen (Attendance) - UI

### ISSUE THREAD

**Issue by Varun-Kolanu** [Varun-Kolanu/csoc_flutter#4]
**Is your feature request related to a problem? Please describe.**
No Home Screen right now

**Describe the solution you'd like**
- Display the Subjects in the timetable on the current Date.
- Also add the footer to navigate between Attendance and Reminders.
- Only the UI for now, logic and APIs have another issue

**Additional context**
UI:

![image](https://github.com/Varun-Kolanu/csoc_flutter/assets/112728411/3c54d5e5-0734-4a98-8d54-9c8f5137451c)

Full Figma: https://www.figma.com/design/SSqE8Fn9qAakayjyhZ9gqf/Attendance-Tracker?node-id=0-1&t=Xpgi43pHobRh2dnD-1

**Comment by devrungta** [comment]
@csoc-bot claim

**Comment by Varun-Kolanu** [comment]
@devrungta cron job panoti dedi achanak 😵‍💫
Abhi karo abse chalne lagega

**Comment by devrungta** [comment]
@csoc-bot claim

**Comment by devrungta** [comment]
Bhaiya, me try kar rha hu ki home screen me bottom navigation bar add karke, vahan se attendance page par aa sakte..

**Comment by devrungta** [comment]
Login karne ke baad home screen blank aa rhi....
check kaise karu bhaiya ki abhi tak attendance page ka ui kaisa dikh rha??

**Comment by devrungta** [comment]
@csoc-bot abandon
