### ISSUE TITLE
[FEAT] Home Screen - Logic and APIs

### ISSUE THREAD

**Issue by Varun-Kolanu** [Varun-Kolanu/csoc_flutter#5]
**Is your feature request related to a problem? Please describe.**
Logic is not added in Attendance.

**Describe the solution you'd like**
- Add Logic in the Home Page Attendance marking using Flutter Firestore
- Also, add the logic for "How many more classes he should attend to reach desired percentage" or "How many more classes he can miss"

**Additional context**
UI for reference: (Though your work is to build only logic)

![image](https://github.com/Varun-Kolanu/csoc_flutter/assets/112728411/01a04d38-cf8b-400f-a864-ed01e7a14829)

Full figma: https://www.figma.com/design/SSqE8Fn9qAakayjyhZ9gqf/Attendance-Tracker?node-id=0-1&t=Xpgi43pHobRh2dnD-1

**Comment by devrungta** [comment]
@csoc-bot claim
