### ISSUE TITLE
[FEAT] Sidebar

### ISSUE THREAD

**Issue by Varun-Kolanu** [Varun-Kolanu/csoc_flutter#8]
**Describe the solution you'd like**
- A beautiful Sidebar
- Including animation to slide in and out

**Additional context**
UI and features in sidebar:

![image](https://github.com/Varun-Kolanu/csoc_flutter/assets/112728411/f91b3f18-6e1b-4a43-9147-4bb1c2f983d9)

Full Figma: [Figma](https://www.figma.com/design/SSqE8Fn9qAakayjyhZ9gqf/Attendance-Tracker?node-id=0-1&t=Xpgi43pHobRh2dnD-1)

**Comment by Rasesh2005** [comment]
@csoc-bol claim

**Comment by Rasesh2005** [comment]
@csoc-bot claim

**Comment by Rasesh2005** [comment]
[Here](https://github.com/Varun-Kolanu/csoc_flutter/assets/65321291/f78aeb49-0c41-408f-952b-2a7c3bee268a)

* Is this Sidebar good enough?? 
* I added notification button on the AppBar
* Changed the color of AppBar( Though it will be made uniform when we add themes, may be i should remove it??)
* Will be changing the icons for other ListTiles in the SideBar as well.. 

**Just want to get feedback on what improvement in design can be made?**

Also.. it can be swiped into and outside on android(Tested on physical device by me 😄 )

**Comment by Rasesh2005** [comment]
@Varun-Kolanu  Please verify

**Comment by Varun-Kolanu** [comment]
@Rasesh2005 Good work out there!
Design is good
Let the app bar be as it is now. You can edit that in the App Bar issue if you would like to take it.
One suggestion, render the username etc of the logged in user using the 'user' variable that is passed to home screen or read it from cubit in context.
